[tool.poetry]
name = "conductor"
version = "0.1.0"
description = ""
authors = ["BannerWang <banner.wang@upblocks.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
