x-base-service: &base-service
  shm_size: 1gb
  build: .
  working_dir: /workspace/Conductor/docker
  env_file:
    - .env
  volumes:
    - /data:/data
    - /${DATASET_SRC}:/${DATASET_SRC}
    - ./..:/workspace/Conductor
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            capabilities: [gpu]
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 5
    window: 120s

services:
  train:
    <<: *base-service
    command: bash -c "bash /workspace/Conductor/conductor/train/train.sh"
    healthcheck:
      test: ["CMD", "python", "/workspace/Conductor/conductor/train/health_check.py", "${DINGDING_TOKEN}", "${HOST_IP}", "${DATASET_NAME}", "${TRAIN_CMD}", "--training_dir", "${TRAINING_DIR}"]
      interval: 60s
      timeout: 60s
      retries: 3
      start_period: 60s

  within_decode:
    <<: *base-service
    command: bash -c "bash /workspace/Conductor/conductor/within_dataset_decode/decode.sh"
    healthcheck:
      test: ["CMD", "python", "/workspace/Conductor/conductor/within_dataset_decode/health_check.py"]
      interval: 60s
      timeout: 60s
      retries: 3
      start_period: 60s