version: '3'
services:
  icefall:
    build: .
    working_dir: /workspace/compose_icefall
    env_file:
      - .env
    volumes:
      - /data:/data
      - ./:/workspace/compose_icefall
    command: bash -c "bash train.sh ${ICEFALL_PATH} ${DATASET} ${TRAIN_CMD} ${LOG_FILE}> ${LOG_FILE} 2>&1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    healthcheck:
      test: ["CMD", "python", "health_check.py", "${DINGDING_TOKEN}"]
      interval: 10s  # 每 10 秒检查一次
      timeout: 5s
      retries: 1
      start_period: 20s  # 容器启动后 20 秒开始健康检查